[package]
name = "funcfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
smartstring = "1.0.1"
thiserror = "1.0.40"

[dev-dependencies]
lazy_static = "1.4.0"
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false
